/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_quoted_string = 2,
  sym_heredoc_operator = 3,
  sym_heredoc_quote = 4,
  sym_redirect = 5,
  sym_variable = 6,
  sym_keyword = 7,
  sym_operator = 8,
  sym_terminator = 9,
  sym_delimiter = 10,
  sym_word = 11,
  sym_heredoc_marker = 12,
  sym_heredoc_body = 13,
  sym_source_file = 14,
  sym_heredoc_redirect = 15,
  aux_sym_source_file_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_quoted_string] = "quoted_string",
  [sym_heredoc_operator] = "heredoc_operator",
  [sym_heredoc_quote] = "heredoc_quote",
  [sym_redirect] = "redirect",
  [sym_variable] = "variable",
  [sym_keyword] = "keyword",
  [sym_operator] = "operator",
  [sym_terminator] = "terminator",
  [sym_delimiter] = "delimiter",
  [sym_word] = "word",
  [sym_heredoc_marker] = "heredoc_marker",
  [sym_heredoc_body] = "heredoc_body",
  [sym_source_file] = "source_file",
  [sym_heredoc_redirect] = "heredoc_redirect",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_quoted_string] = sym_quoted_string,
  [sym_heredoc_operator] = sym_heredoc_operator,
  [sym_heredoc_quote] = sym_heredoc_quote,
  [sym_redirect] = sym_redirect,
  [sym_variable] = sym_variable,
  [sym_keyword] = sym_keyword,
  [sym_operator] = sym_operator,
  [sym_terminator] = sym_terminator,
  [sym_delimiter] = sym_delimiter,
  [sym_word] = sym_word,
  [sym_heredoc_marker] = sym_heredoc_marker,
  [sym_heredoc_body] = sym_heredoc_body,
  [sym_source_file] = sym_source_file,
  [sym_heredoc_redirect] = sym_heredoc_redirect,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_heredoc_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_heredoc_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_redirect] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_terminator] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_heredoc_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_heredoc_body] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_heredoc_redirect] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static const TSCharacterRange sym_word_character_set_1[] = {
  {0, 0x08}, {0x0b, '\f'}, {0x0e, 0x1f}, {'"', '"'}, {'%', '%'}, {'*', ':'}, {'?', '?'}, {'A', ']'},
  {'_', '_'}, {'a', 'z'}, {0x7f, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '#', 13,
        '$', 28,
        '&', 27,
        '\'', 18,
        '<', 20,
        '>', 21,
        '\\', 10,
        'c', 32,
        'e', 39,
        'f', 41,
        'i', 46,
        's', 45,
        'w', 36,
        '|', 29,
        '\n', 30,
        ';', 30,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '(' ||
          lookahead == ')' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(31);
      if (lookahead == '!' ||
          lookahead == '=' ||
          lookahead == '@' ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(26);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '*' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(14);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == ']') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == ']') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ']') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == ']') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '#', 13,
        '$', 28,
        '&', 27,
        '\'', 2,
        '<', 20,
        '>', 21,
        '\\', 10,
        'c', 32,
        'e', 39,
        'f', 41,
        'i', 46,
        's', 45,
        'w', 36,
        '|', 29,
        '\n', 30,
        ';', 30,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11);
      if (lookahead == '(' ||
          lookahead == ')' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(31);
      if (lookahead == '!' ||
          lookahead == '=' ||
          lookahead == '@' ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(26);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_quoted_string);
      if (lookahead == '\'') ADVANCE(2);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_heredoc_operator);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_heredoc_operator);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead == '[') ADVANCE(9);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_heredoc_quote);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_heredoc_quote);
      if (lookahead == '\'') ADVANCE(14);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_redirect);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_redirect);
      if (lookahead == '<') ADVANCE(16);
      if (lookahead == '[') ADVANCE(8);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_redirect);
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == '[') ADVANCE(8);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_redirect);
      if (lookahead == '[') ADVANCE(8);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_variable);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '*' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == '\\') ADVANCE(10);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '&') ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '"' ||
          lookahead == '#' ||
          lookahead == '^') ADVANCE(1);
      if (lookahead == '*' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '|') ADVANCE(26);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_terminator);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_delimiter);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'a') ADVANCE(43);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'c') ADVANCE(35);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'e') ADVANCE(25);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'h') ADVANCE(25);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'h') ADVANCE(38);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'i') ADVANCE(44);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'i') ADVANCE(40);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'l') ADVANCE(43);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'l') ADVANCE(34);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(42);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'r') ADVANCE(25);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 's') ADVANCE(34);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 't') ADVANCE(33);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'w') ADVANCE(37);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 'f' ||
          lookahead == 'n') ADVANCE(25);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\\') ADVANCE(10);
      if ((!eof && set_contains(sym_word_character_set_1, 11, lookahead))) ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 3, .external_lex_state = 2},
  [8] = {.lex_state = 3, .external_lex_state = 3},
  [9] = {.lex_state = 3, .external_lex_state = 3},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_heredoc_operator] = ACTIONS(1),
    [sym_heredoc_quote] = ACTIONS(1),
    [sym_redirect] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_terminator] = ACTIONS(1),
    [sym_delimiter] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_heredoc_marker] = ACTIONS(1),
    [sym_heredoc_body] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(10),
    [sym_heredoc_redirect] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_quoted_string] = ACTIONS(5),
    [sym_heredoc_operator] = ACTIONS(7),
    [sym_redirect] = ACTIONS(5),
    [sym_variable] = ACTIONS(5),
    [sym_keyword] = ACTIONS(9),
    [sym_operator] = ACTIONS(9),
    [sym_terminator] = ACTIONS(5),
    [sym_delimiter] = ACTIONS(5),
    [sym_word] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_heredoc_redirect] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
    [sym_quoted_string] = ACTIONS(13),
    [sym_heredoc_operator] = ACTIONS(7),
    [sym_redirect] = ACTIONS(13),
    [sym_variable] = ACTIONS(13),
    [sym_keyword] = ACTIONS(15),
    [sym_operator] = ACTIONS(15),
    [sym_terminator] = ACTIONS(13),
    [sym_delimiter] = ACTIONS(13),
    [sym_word] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_heredoc_redirect] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_comment] = ACTIONS(19),
    [sym_quoted_string] = ACTIONS(19),
    [sym_heredoc_operator] = ACTIONS(22),
    [sym_redirect] = ACTIONS(19),
    [sym_variable] = ACTIONS(19),
    [sym_keyword] = ACTIONS(25),
    [sym_operator] = ACTIONS(25),
    [sym_terminator] = ACTIONS(19),
    [sym_delimiter] = ACTIONS(19),
    [sym_word] = ACTIONS(25),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(28),
    [sym_comment] = ACTIONS(28),
    [sym_quoted_string] = ACTIONS(28),
    [sym_heredoc_operator] = ACTIONS(30),
    [sym_redirect] = ACTIONS(28),
    [sym_variable] = ACTIONS(28),
    [sym_keyword] = ACTIONS(30),
    [sym_operator] = ACTIONS(30),
    [sym_terminator] = ACTIONS(28),
    [sym_delimiter] = ACTIONS(28),
    [sym_word] = ACTIONS(30),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(32),
    [sym_comment] = ACTIONS(32),
    [sym_quoted_string] = ACTIONS(32),
    [sym_heredoc_operator] = ACTIONS(34),
    [sym_redirect] = ACTIONS(32),
    [sym_variable] = ACTIONS(32),
    [sym_keyword] = ACTIONS(34),
    [sym_operator] = ACTIONS(34),
    [sym_terminator] = ACTIONS(32),
    [sym_delimiter] = ACTIONS(32),
    [sym_word] = ACTIONS(34),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(36),
    [sym_comment] = ACTIONS(36),
    [sym_quoted_string] = ACTIONS(36),
    [sym_heredoc_operator] = ACTIONS(38),
    [sym_redirect] = ACTIONS(36),
    [sym_variable] = ACTIONS(36),
    [sym_keyword] = ACTIONS(38),
    [sym_operator] = ACTIONS(38),
    [sym_terminator] = ACTIONS(36),
    [sym_delimiter] = ACTIONS(36),
    [sym_word] = ACTIONS(38),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(40), 1,
      sym_heredoc_quote,
    ACTIONS(42), 1,
      sym_heredoc_marker,
  [7] = 2,
    ACTIONS(44), 1,
      sym_heredoc_quote,
    ACTIONS(46), 1,
      sym_heredoc_body,
  [14] = 2,
    ACTIONS(48), 1,
      sym_heredoc_quote,
    ACTIONS(50), 1,
      sym_heredoc_body,
  [21] = 1,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
  [25] = 1,
    ACTIONS(54), 1,
      sym_heredoc_marker,
  [29] = 1,
    ACTIONS(50), 1,
      sym_heredoc_body,
  [33] = 1,
    ACTIONS(56), 1,
      sym_heredoc_body,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 7,
  [SMALL_STATE(9)] = 14,
  [SMALL_STATE(10)] = 21,
  [SMALL_STATE(11)] = 25,
  [SMALL_STATE(12)] = 29,
  [SMALL_STATE(13)] = 33,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heredoc_redirect, 3, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heredoc_redirect, 3, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heredoc_redirect, 4, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heredoc_redirect, 4, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heredoc_redirect, 5, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heredoc_redirect, 5, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [52] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_heredoc_marker = 0,
  ts_external_token_heredoc_body = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_heredoc_marker] = sym_heredoc_marker,
  [ts_external_token_heredoc_body] = sym_heredoc_body,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_heredoc_marker] = true,
    [ts_external_token_heredoc_body] = true,
  },
  [2] = {
    [ts_external_token_heredoc_marker] = true,
  },
  [3] = {
    [ts_external_token_heredoc_body] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_rcsh_external_scanner_create(void);
void tree_sitter_rcsh_external_scanner_destroy(void *);
bool tree_sitter_rcsh_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_rcsh_external_scanner_serialize(void *, char *);
void tree_sitter_rcsh_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rcsh(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_rcsh_external_scanner_create,
      tree_sitter_rcsh_external_scanner_destroy,
      tree_sitter_rcsh_external_scanner_scan,
      tree_sitter_rcsh_external_scanner_serialize,
      tree_sitter_rcsh_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "rcsh",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
